-- 코드를 입력하세요
WITH A as (
    SELECT FP.PRODUCT_ID,	PRODUCT_NAME,	PRODUCT_CD,	CATEGORY,	PRICE,AMOUNT
    FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
    where PRODUCE_DATE BETWEEN '2022-05-01' and '2022-05-31'
)




SELECT PRODUCT_ID,	PRODUCT_NAME, SUM(AMOUNT) * PRICE as TOTAL_SALES
FROM A
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID