-- 코드를 작성해주세요

WITH A as (
    SELECT * 
    FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
),

B as (
SELECT IT.ITEM_ID

FROM A JOIN ITEM_TREE IT ON A.ITEM_ID = IT.PARENT_ITEM_ID

)

SELECT II.ITEM_ID, ITEM_NAME, RARITY

FROM B JOIN ITEM_INFO II ON B.ITEM_ID = II.ITEM_ID

ORDER BY II.ITEM_ID DESC