-- 코드를 입력하세요
# SELECT FLAVOR
# FROM (SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER > 3000 ORDER BY TOTAL_ORDER DESC) as a
# WHERE 

SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'