-- 코드를 작성해주세요



#SELECT MAX(LENGTH)  FROM FISH_INFO GROUP BY FISH_TYPE

#SELECT ID, FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE HAVING LENGTH = MAX(LENGTH)

SELECT ID, FISH_NAME, LENGTH

FROM ( SELECT FI.ID, NI.FISH_NAME,FI.LENGTH, MAX(FI.LENGTH) OVER(PARTITION BY FI.FISH_TYPE) MAX_LEN
     FROM FISH_INFO FI JOIN FISH_NAME_INFO NI ON FI.FISH_TYPE = NI.FISH_TYPE
     ) TMP
WHERE TMP.LENGTH = TMP.MAX_LEN
ORDER BY ID